### ISSUE TITLE
Global labels & annotations

### ISSUE THREAD

**Issue by MikeAtJulaya** [windmill-labs/windmill-helm-charts#58]
Hi team 👋🏼 

It would be nice to have a global rewriting of labels and annotations on top. Cause on my IDP (Qovery) there are some missing and I can't:
- display services logs
- stop the chart
- display services statuses

For example:
```yaml
windmill:
    annotations:
      qovery.annotations.service
    labels:
      qovery.labels.service
```

I'm available for testing if needed 👌🏼 
cheers 🍻
