### ISSUE TITLE
Replicas seems to not working

### ISSUE THREAD

**Issue by MikeAtJulaya** [windmill-labs/windmill-helm-charts#59]
Hi team 👋🏼 

I'm using Windmill chart on Qovery IDP for context.

But when I change replicas it doesn't seems to change the number of workers:
<img width="1478" alt="Screenshot 2024-02-16 at 10 13 59" src="https://github.com/windmill-labs/windmill-helm-charts/assets/127132677/bfb888fa-b6be-471f-9b71-165f42104f08">

Here my rewrite values for testing purposes:
```yaml
postgresql:
  enabled: false
windmill:
    databaseUrl: qovery.env.DATABASE_URL
    annotations:
      qovery.annotations.service
    labels:
      qovery.labels.service
workerGroups:
  - name: "default"
    replicas: 2
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1024Mi"
        cpu: "1000m"
    annotations:
      qovery.annotations.service
    labels:
      qovery.labels.service
  - name: "native"
    replicas: 0
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "100m"
    annotations:
      qovery.annotations.service
    labels:
      qovery.labels.service
  - name: "gpu"
    annotations:
      qovery.annotations.service
    labels:
      qovery.labels.service
app:
  annotations:
    qovery.annotations.service
  labels:
    qovery.labels.service
lsp:
  annotations:
    qovery.annotations.service
  labels:
    qovery.labels.service
multiplayer:
  annotations:
    qovery.annotations.service
  labels:
    qovery.labels.service
ingress:
  enabled: false
serviceAccount:
  annotations:
    qovery.annotations.service
```

available for testing if needed 👌🏼 
Cheers
