### ISSUE TITLE
Helm Chart rendering RunAsRoot at the wrong indent

### ISSUE THREAD

**Issue by avo-sepp** [windmill-labs/windmill-helm-charts#63]
![Screenshot 2024-02-27 at 10 46 58](https://github.com/windmill-labs/windmill-helm-charts/assets/68659218/5b56ae73-f102-4cce-b317-8862226ea951)

See image. RunAsRoot is not being saved to Kubernetes because it is being rendered one tier above SecurityContext. It should be nested under SecurityContext.

**Comment by avo-sepp** [comment]
More info, this problem is seen on `native` and `default` worker groups. I don't think we're running any other worker groups, so I cannot confirm/deny those.

**Comment by rubenfiszel** [comment]
@avo-sepp can you share the values you are using ?

**Comment by avo-sepp** [comment]
```windmill:
  baseDomain: "redacted"
  baseProtocol: "https"
  databaseUrlSecretName: "redacted"
  databaseUrlSecretKey: url
postgresql:
  enabled: false
ingress:
  enabled: true
  className: "nginx"
  tls:
    - hosts:
        - "redacted"
      secretName: redacted 
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
```

**Comment by avo-sepp** [comment]
The Helm chart is being rendered and applied by ArgoCD. When rendered on the CLI the indenting is off. It looks like...

```
      containers:
      - name: windmill-worker

        securityContext:

            runAsNonRoot: false
            runAsUser: 0



        image: ghcr.io/windmill-labs/windmill:1.278.5

        imagePullPolicy: Always
        ports:
        - containerPort: 8001
```
