### ISSUE TITLE
Please use the image `windmill-full` for your instance in order to run rust jobs.

### ISSUE THREAD

**Issue by myst3k** [windmill-labs/windmill-helm-charts#77]
Just found Windmill, and installed with helm chart. Getting this error when trying to run a Rust script. I couldn't find any windmill-full images on the repos to change the image/tag to in the Helm Values.

```
ExecutionErr: error during execution of the script:
Not found: Couldn't find cargo at /usr/local/cargo/bin/cargo. This probably means that you are not using the windmill-full image. Please use the image `windmill-full` for your instance in order to run rust jobs.
```

Using a basic values file.

```
windmill:
  baseDomain: "my.home.domain"
  tag: "1.394.3"

ingress:
  enabled: true
  className: "nginx"
```
