### ISSUE TITLE
GKE Ingress config requires a single host with multiple paths

### ISSUE THREAD

**Issue by BennetVellaExient** [windmill-labs/windmill-helm-charts#94]
> If you want to configure GKE Ingress with multiple backends for the same host, you must have a single rule with a single host and multiple paths. Otherwise, the GKE ingress controller provisions only one backend service

Source: https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#multiple_backend_services

But the helm ingress.yaml creates multiple hosts: https://github.com/windmill-labs/windmill-helm-charts/blob/4a71fc7c8a94e5a72411695156375795f36ae9e3/charts/windmill/templates/ingress.yaml#L25

Can confirm that combining the paths under a single host correctly updated the load balancer to map properly

So as a practical example, what I was getting by default helm configuration:

```yaml
 spec:
    rules:
    - host: windmill.blabla
      http:
        paths:
        - backend:
            service:
              name: windmill-lsp
              port:
                number: 3001
          path: /ws/
          pathType: Prefix
    - host: windmill.blabla
      http:
        paths:
        - backend:
            service:
              name: windmill-app
              port:
                number: 8000
          path: /
          pathType: Prefix
```

For GKE, the expected setup should be as follows:

```yaml
 spec:
    rules:
    - host: windmill.blabla
      http:
        paths:
        - backend:
            service:
              name: windmill-lsp
              port:
                number: 3001
          path: /ws/
          pathType: Prefix
        - backend:
            service:
              name: windmill-app
              port:
                number: 8000
          path: /
          pathType: Prefix
```

I don't know if a shared host with multiple paths might then conflict with a different provider, but can confirm that GKE requires a single host.
