### ISSUE TITLE
Incompatible configuration options volumes and exposeHostDocker

### ISSUE THREAD

**Issue by akopper** [windmill-labs/windmill-helm-charts#97]
Either of the options work. When both are specified, invalid yaml is rendered.

windmill.workergroups.exposeHostDocker and windmill.workergroups.volumes

Reason is in worker-groups.yaml:197. Mixed indentation of docker volume definition with volume from values file. 

sample config mounting a ConfigMap:
```yaml
 windmill:
  workerGroups:
    - affinity: {}
      annotations: {}
      command: []
      containerSecurityContext: {}
      controller: Deployment
      exposeHostDocker: true
      extraContainers: []
      extraEnv:
        - name: KUBECONFIG
          value: /etc/kube/kube.conf
      initContainers: []
      labels: {}
      mode: worker
      name: default
      nodeSelector: {}
      podSecurityContext:
        runAsNonRoot: false
        runAsUser: 0
      replicas: 3
      resources:
        limits:
          memory: 2Gi
      terminationGracePeriodSeconds: 604800
      tolerations: []
      volumeClaimTemplates: []
      volumes:
        - name: kubeconfig-vol
          configMap:
            name: kube-config
      volumeMounts:
        - name: kubeconfig-vol
          mountPath: /etc/kube
          readOnly: true`
```
